version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "depbot(docs): "
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "tailwindcss"
        versions:
          - "*"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "depbot(web): "
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
