name: Format

on:
    pull_request:
        branches: [main]

jobs:
    format:
        name: Prettier Check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - run: npm ci

            - run: npx prettier --check "**/*.{ts,tsx,md}"
